# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.getRiskVariantMatrixDetails <- function(model, popfile, popfile_offset, dominance = 0.) {
    .Call('diseaseSims_getRiskVariantMatrixDetails', PACKAGE = 'diseaseSims', model, popfile, popfile_offset, dominance)
}

.getRiskVariantMatrixDetailsPheno <- function(model, popfile, popfile_offset, phenofile, phenofile_offset, dominance = 0.) {
    .Call('diseaseSims_getRiskVariantMatrixDetails_Pheno', PACKAGE = 'diseaseSims', model, popfile, popfile_offset, phenofile, phenofile_offset, dominance)
}

#' Manage access to a gz-compressed file
#' @param filename The file name to write to
#' @param mode The mode for opening the file.
#' @return An external pointer to a boostScopedLockManager
gzLock <- function(filename, mode) {
    .Call('diseaseSims_initZlibBoostScopedLock', PACKAGE = 'diseaseSims', filename, mode)
}

#' Unlock and close a gz-compressed file
#' @param s A boostScopedLockManager
gzUnlock <- function(s) {
    invisible(.Call('diseaseSims_endZlibBoostScopedLock', PACKAGE = 'diseaseSims', s))
}

#' Write a data frame to file
#' @param s A data frame
#' @param locker A boostScopedLockManager
#' @param colnames If TRUE, write column names to file
#' @param sep column separater
writeDataFrame <- function(s, locker, colnames = TRUE, sep = "\t") {
    .Call('diseaseSims_writeDataFrame', PACKAGE = 'diseaseSims', s, locker, colnames, sep)
}

#' Write a matrix to file
#' @param s A matrix
#' @param locker A boostScopedLockManager
#' @param colnames If TRUE, write column names to file
#' @param sep column separater
writeMatrix <- function(s, locker, colnames = TRUE, sep = "\t") {
    .Call('diseaseSims_writeMatrix', PACKAGE = 'diseaseSims', s, locker, colnames, sep)
}

#' Read effect sizes from a file at a specific position
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
getEsizes <- function(filename, offset) {
    .Call('diseaseSims_getEsizes', PACKAGE = 'diseaseSims', filename, offset)
}

#' Sample a case/control panel from a population.
#' This is used for "on the fly" analysis in place of the make_case_control program,
#' for cases where the user may not want to write a case/control panel to file.
#' @param popfilename  The name of the population file (gzipped, binary)
#' @param offset  The offset of the record in popfilename
#' @param phenofilename The name of the file recording phenotypes (gzipped, binary)
#' @param phenooffset The offset of the record in phenofilename
#' @param ncontrols The number of controls to sample
#' @param ncases The number of cases to sample
#' @param case_proportion The incidence of the disease.  Thus, an individual whose trait value is >= the 1 - case_proportion'th quantile of trait values in the population is a potential case
#' @param control_range A putative control individual is defined as mean +/- control_range*sd, where mean and sd refer to the distribution of the phenotype in the entire population.
#' @param seed Random number seed
sampleCCfromPop <- function(popfilename, offset, phenofilename, phenooffset, ncontrols, ncases, case_proportion, control_range, seed) {
    .Call('diseaseSims_sampleCCfromPop', PACKAGE = 'diseaseSims', popfilename, offset, phenofilename, phenooffset, ncontrols, ncases, case_proportion, control_range, seed)
}

#' Read case/control panel from a file at a specific position
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
getCCblock <- function(filename, offset) {
    .Call('diseaseSims_getCCblock', PACKAGE = 'diseaseSims', filename, offset)
}

#' Read case/control ids from a file at a specific position
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
#' @return A list of who the controls and cases were.  These are values between 1 and N, the population size.
getCCids <- function(filename, offset) {
    .Call('diseaseSims_getCCids', PACKAGE = 'diseaseSims', filename, offset)
}

#' Read case/control panel from a file at a specific position
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
getPheno <- function(filename, offset) {
    .Call('diseaseSims_getPheno', PACKAGE = 'diseaseSims', filename, offset)
}

#' Site frequency spectra
#' @param popfile The file containing the simulated populations
#' @param n The desired sample size.  If n == 2N, the entire population is sampled
#' @param seed A random number seed
#' @return A data frame with 4 columns:
#' @return replicate = an arbitrary sample ID.  This is NOT the same ID number as the user may have assigned when running the simulation!!
#' @return i = the number of occurences of a mutation in the population/sample
#' @return n = the SFS for neutral variants
#' @return r = the SFS for risk variants
sfs <- function(popfile, n, seed = 0L) {
    .Call('diseaseSims_sfs', PACKAGE = 'diseaseSims', popfile, n, seed)
}

#' Write the results of an association test to a file
#' @param outfilename Output file name
#' @param indexfilename Index file name for the output
#' @param recordno An unsigned integer to use as a label for pvblock.
#' @param pvblock A data frame. The return value of \link[diseaseSims]{makePVblock}.
#' @param append  Boolean: append to output files or not?
#' @param gzip Boolean: write compressed data or not?
#' @details If append == TRUE, then file output is handled by low-level 
#' POSIX file locking via the C header
#' <fcntl.h>.  In practice, most file systems support this, but if you get
#' garbled output, yours may not.  The index file is locked, then the main
#' output is written and outfilename is closed.  The index data are then written,
#' and file locks are then released.
#'
#' If append == FALSE, then no file locking is done, which means
#' different R processes should write to different output files,
#' otherwise you'll be overwriting your data!!!!
#' @note This function should be viewed as deprecated, and replaced by writeDataFrame
writePVblock <- function(outfilename, indexfilename, recordno, pvblock, append = TRUE, gzip = FALSE) {
    invisible(.Call('diseaseSims_writePVblock', PACKAGE = 'diseaseSims', outfilename, indexfilename, recordno, pvblock, append, gzip))
}

