# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib diseaseSims, .registration=TRUE
#' @exportPattern "^[[:alpha:]]+"
#' @import methods
#' @import inline
#' @importFrom Rcpp evalCpp loadModule Module
NULL

#' Reads in the entire population
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
readPop <- function(filename, offset) {
    .Call('diseaseSims_readPop', PACKAGE = 'diseaseSims', filename, offset)
}

#' Read effect sizes from a file
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
getEsizes <- function(filename, offset) {
    .Call('diseaseSims_getEsizes', PACKAGE = 'diseaseSims', filename, offset)
}

#' Read case/control panel from a file
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
getCCblock <- function(filename, offset) {
    .Call('diseaseSims_getCCblock', PACKAGE = 'diseaseSims', filename, offset)
}

#' Read case/control panel from a file
#' @param filename The file name.  Should be binary, and either uncompressed or gzip compressed.
#' @param offset The size in bytes where the desired record begins
getPheno <- function(filename, offset) {
    .Call('diseaseSims_getPheno', PACKAGE = 'diseaseSims', filename, offset)
}

