---
title: "Handling of index files"
author: "Kevin Thornton"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Handling of index files}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

#Intro

This vignette covers how to properly handle the index files generated by the simulation software, etc.

The index files are quite simple, containing an ID for a specific replicate, and then the size of that replicate (in bytes).

The trick, as far as R is concerned, is that a simple read.table on an index file will be return integer data (currently 32 bits in R).  However, we require a 64-bit representation for these sizes in order to read records from large files.  We can do that be reading in the index as a numeric type.

## Manual processing 

For example, to read in the index file generated by TFL2013_ind, this will do the trick:

~~~{r}
##idx will contain the replicate ID and the sizes of the effects block, 
##phenotypes block, and simulated populations, respectively, on each row
idx = read.table("simindex.txt",colClasses=c("integer",rep("numeric",3)))
~~~

Now let's say that you want to get the offset where the i-th simulated population can be found:

~~~{r}
z = which(idx$V1 == i)
##If the i-th rep is on the first row of the file,
##then it starts at an offset of 0.  Else, it begins
##at the sum of all preceeding rows.
offset = ifelse( i == 1, 0, sum(idx$V4[1:(i-1)]) )
~~~

The index for the case/control archives are handled similarly, except that there are only two columns -- replicate ID and size of the record in bytes.

## Automated processed

The R package provides diseaseSims::procIndex, which basically implements the previous section. See the following help:

~~~{r}
library(diseaseSims)
help(procIndex)
~~~